mutation createCard(
  $boardId: String!
  $columnId: String!
  $title: String!
  $content: String!
  $type: String!
  $score: String!
  $scoreType: String!
  $order: Int!
) {
  createCard(
    boardId: $boardId
    columnId: $columnId
    title: $title
    content: $content
    type: $type
    score: $score
    scoreType: $scoreType
    order: $order
  ) {
    id
  }
}
